/* external_strings.cpp is automatically generated. Do not edit this file.
 * It exists solely for the purpose of Gettext's xgettext(1) command to
 * pick them up for translation purposes. Run rake i18n:potfile to update
 * this file. */
#if 0
static const char* exttrans1 = _("This is a signpost!<NM>It took about a week to code it!");
#endif
